# Generated by Django 5.0.1 on 2025-01-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('shipped', 'Shipped'), ('completed', 'Completed')], default='received', max_length=10),
        ),
    ]
